import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styled from 'styled-components'

const Main = styled.main`
  padding: 32px 24px;
  font-size: 20px;
`

const Footer = styled.footer`
  width: 100%;
  background-color: #CECFF9;
  color: #151951;
  font-size: 24px;
  padding: 8px 24px 24px;
  position: absolute;
  bottom: 0;

  a {
    padding: 8px 24px;
    display: inline-block;
    min-width: 150px;
    text-align: center;

    &.selected {
      background: #babad4;
      border-radius: 10px;
    }
  }
`

const GuideRow = styled.div`
  display: flex;
`

const Item = styled.div`
  background-color: rgba(48, 56, 131, 0.5);
  border-radius: 10px;
  width: 200px;
  margin-right: 4px;
  padding: 8px 16px;
  margin-bottom: 4px;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
`

const Channel = styled(Item)`
  background: #252657;
  width: 200px;
  flex: none;
  margin-right: 8px;
`

const Timeline = styled(GuideRow)`
  ${Channel}, ${Item} {
    background: transparent;
    font-size: 18px;
    margin-bottom: 0;
  }
`

const Scrollable = styled.div`
  display: flex;
`


const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next AppTest change</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <Timeline>
          <Channel />
          <Scrollable>
            <Item>Now</Item>
            <Item>Programme</Item>
            <Item>Programme</Item>
            <Item>Programme</Item>
            <Item>Programme</Item>
          </Scrollable>
        </Timeline>
        <GuideRow>
          <Channel>BBC One</Channel>
          <Scrollable>
            <Item>Coming soon</Item>
          </Scrollable>
        </GuideRow>
        <GuideRow>
          <Channel>BBC Two</Channel>
          <Scrollable>
            <Item>Coming soon</Item>
          </Scrollable>
        </GuideRow>
        <GuideRow>
          <Channel>ITV</Channel>
          <Scrollable>
            <Item>Coming soon</Item>
          </Scrollable>
        </GuideRow>
        <GuideRow>
          <Channel>Channel 4</Channel>
          <Scrollable>
            <Item>Coming soon</Item>
          </Scrollable>
        </GuideRow>
        <GuideRow>
          <Channel>Channel 5</Channel>
          <Scrollable>
            <Item>Coming soon</Item>
          </Scrollable>
        </GuideRow>
        <GuideRow>
          <Channel>Sky Sports F1</Channel>
          <Scrollable>
            <Item>Programme</Item>
            <Item>Programme</Item>
            <Item>Programme</Item>
            <Item>Programme</Item>
            <Item>Programme</Item>
          </Scrollable>
        </GuideRow>
        <GuideRow>
          <Channel>Sky Sports Cricket</Channel>
          <Scrollable>
            <Item>Programme</Item>
            <Item>Programme</Item>
            <Item>Programme</Item>
            <Item>Programme</Item>
            <Item>Programme</Item>
          </Scrollable>
        </GuideRow>
        <GuideRow>
          <Channel>Sky Sports Main Event</Channel>
          <Scrollable>
            <Item>Programme</Item>
            <Item>Programme</Item>
            <Item>Programme</Item>
            <Item>Programme</Item>
            <Item>Programme</Item>
          </Scrollable>
        </GuideRow>
        <GuideRow>
          <Channel>Sky Sports Action</Channel>
          <Scrollable>
            <Item>Programme</Item>
            <Item>Programme</Item>
            <Item>Programme</Item>
            <Item>Programme</Item>
            <Item>Programme</Item>
          </Scrollable>
        </GuideRow>
        <GuideRow>
          <Channel>Sky Sports Arena</Channel>
          <Scrollable>
            <Item>Programme</Item>
            <Item>Programme</Item>
            <Item>Programme</Item>
            <Item>Programme</Item>
            <Item>Programme</Item>
          </Scrollable>
        </GuideRow>
        <GuideRow>
          <Channel>ITV 2</Channel>
          <Scrollable>
            <Item>Coming soon</Item>
          </Scrollable>
        </GuideRow>
        <GuideRow>
          <Channel>ITV 4</Channel>
          <Scrollable>
            <Item>Coming soon</Item>
          </Scrollable>
        </GuideRow>
        <GuideRow>
          <Channel>Sky Sports PL</Channel>
          <Scrollable>
            <Item>Programme</Item>
            <Item>Programme</Item>
            <Item>Programme</Item>
            <Item>Programme</Item>
            <Item>Programme</Item>
          </Scrollable>
        </GuideRow>
        <GuideRow>
          <Channel>Sky Sports Football</Channel>
          <Scrollable>
            <Item>Programme</Item>
            <Item>Programme</Item>
            <Item>Programme</Item>
            <Item>Programme</Item>
            <Item>Programme</Item>
          </Scrollable>
        </GuideRow>
        <GuideRow>
          <Channel>Sky Sports Golf</Channel>
          <Scrollable>
            <Item>Programme</Item>
            <Item>Programme</Item>
            <Item>Programme</Item>
            <Item>Programme</Item>
            <Item>Programme</Item>
          </Scrollable>
        </GuideRow>
        <GuideRow>
          <Channel>Sky Sports Mix</Channel>
          <Scrollable>
            <Item>Programme</Item>
            <Item>Programme</Item>
            <Item>Programme</Item>
            <Item>Programme</Item>
            <Item>Programme</Item>
          </Scrollable>
        </GuideRow>
      </Main>

      <Footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
          className="selected"
        >
          Guide
        </a>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Streaming
        </a>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Watchlist
        </a>
      </Footer>
    </div>
  )
}

export default Home
