import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styled from 'styled-components'

const Main = styled.div`
  padding: 32px;
  font-size: 28px;
`

const GuideRow = styled.div`
  display: flex;
`

const Item = styled.div`
  background-color: rgba(48, 56, 131, 0.5);
  border-radius: 10px;
  width: 200px;
  margin-right: 4px;
  padding: 8px 16px;
`

const Channel = styled(Item)`
  background: #252657;
  width: 280px;
  margin-right: 8px;
  margin-bottom: 4px;
`

const Scrollable = styled.div`
  display: flex;
`


const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next AppTest change</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <GuideRow>
          <Channel>BBC One</Channel>
          <Scrollable>
            <Item>Programme</Item>
            <Item>Programme</Item>
            <Item>Programme</Item>
            <Item>Programme</Item>
            <Item>Programme</Item>
          </Scrollable>
        </GuideRow>
        <GuideRow>
          <Channel>Sky Sports F1</Channel>
          <Scrollable>
            <Item>Programme</Item>
            <Item>Programme</Item>
            <Item>Programme</Item>
            <Item>Programme</Item>
            <Item>Programme</Item>
          </Scrollable>
        </GuideRow>
        <GuideRow>
          <Channel>Sky Sports Cricket</Channel>
          <Scrollable>
            <Item>Programme</Item>
            <Item>Programme</Item>
            <Item>Programme</Item>
            <Item>Programme</Item>
            <Item>Programme</Item>
          </Scrollable>
        </GuideRow>
        <GuideRow>
          <Channel>BBC One</Channel>
          <Scrollable>
            <Item>Programme</Item>
            <Item>Programme</Item>
            <Item>Programme</Item>
            <Item>Programme</Item>
            <Item>Programme</Item>
          </Scrollable>
        </GuideRow>
        <GuideRow>
          <Channel>BBC One</Channel>
          <Scrollable>
            <Item>Programme</Item>
            <Item>Programme</Item>
            <Item>Programme</Item>
            <Item>Programme</Item>
            <Item>Programme</Item>
          </Scrollable>
        </GuideRow>
        <GuideRow>
          <Channel>BBC One</Channel>
          <Scrollable>
            <Item>Programme</Item>
            <Item>Programme</Item>
            <Item>Programme</Item>
            <Item>Programme</Item>
            <Item>Programme</Item>
          </Scrollable>
        </GuideRow>
        <GuideRow>
          <Channel>BBC One</Channel>
          <Scrollable>
            <Item>Programme</Item>
            <Item>Programme</Item>
            <Item>Programme</Item>
            <Item>Programme</Item>
            <Item>Programme</Item>
          </Scrollable>
        </GuideRow>
        <GuideRow>
          <Channel>BBC One</Channel>
          <Scrollable>
            <Item>Programme</Item>
            <Item>Programme</Item>
            <Item>Programme</Item>
            <Item>Programme</Item>
            <Item>Programme</Item>
          </Scrollable>
        </GuideRow>
      </Main>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
