import moment from 'moment'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import styled from 'styled-components'
import { Timeline } from '../components/Timeline'
import { getGuideData, GuideData } from './api/guide'


const Streaming: NextPage = () => {
  
  return (
    <div>
      <Head>
        <title>Create Next AppTest change</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>Page</main>
    </div>
  )
}

export default Streaming
